name = "cognizo-cf-worker"
main = "build/index.js"
compatibility_date = "2025-10-14"
workers_dev = false
preview_urls = false

[build]
command = "./build.sh"


[vars]
TRAFFIC_ANALYTICS_API_URL = "https://traffic-analytics.cognizo.ai"
TRACKING_CODE = "dd572ca226554bb98b98a7814fd6352b8393f4f3c1086cd0e9114ccddcd74dce"
# EXCLUDE_PATHS = ""  # Uncomment to exclude custom paths

[observability]
[observability.logs]
enabled = true
head_sampling_rate = 1
invocation_logs = true